import { ReactElement } from 'react';
import { PropertyCard } from '@ui/property-card';
import Head from 'next/head';
import { Layout } from 'src/layouts';
import { properties } from 'src/lib/properties';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="mx-auto max-w-7xl px-4 xl:px-0">
        <div className="bg-white">
          <div className="mx-auto max-w-7xl px-4 xl:px-0">
            <div className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {properties.map((property, propertyIdx) => (
                <PropertyCard key={propertyIdx} {...property} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
