import { ReactElement, useState } from 'react';
import { HomeCard } from '@ui/home-card';
import Head from 'next/head';
import { Layout } from 'src/layouts';
import { homes } from 'src/lib/homes';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const [wishList, setWishList] = useState<string[]>([]);

  const handleAddToFavorite = (id: string) => {
    setWishList((prev) => {
      if (!prev.includes(id)) {
        return prev.concat(id);
      }

      return prev.filter((p) => p !== id);
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="mx-auto max-w-7xl px-4 xl:px-0">
        <div className="bg-white">
          <div className="wrapper">
            <div className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {homes.map((home, homeIdx) => {
                return (
                  <HomeCard
                    key={homeIdx}
                    {...home}
                    addToFavorite={handleAddToFavorite}
                    isFavorite={wishList.indexOf(home.id) !== -1}
                  />
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
